### ISSUE TITLE
Title escapes LaTeX Math

### ISSUE THREAD

**Issue by amundmr** [kmaasrud/mdoc#62]
Good morning my dear friend.

The title inserted in the toml escapes my LaTeX math! Please have a look at the attached image.

![image](https://user-images.githubusercontent.com/54708595/155279040-f0def691-3aa1-4aae-806d-12ebed79edfb.png)

Best regardus
Amundios

**Comment by kmaasrud** [comment]
Thank you for the informative description and image, friend! I will have a look at this issue at once
